#!/bin/sh
# source: https://github.com/mcullan/jupyter-actions
# Please note that you need to configure this git variable locally: git config --local core.hooksPath .githooks

# Get all notebooks currently staged for commit
notebooks=`git diff --cached --name-only --diff-filter=d | grep  .ipynb`

# Checks if $notebooks is non-empty
if [ ! -z "$notebooks" ]
then
    # Run the script to clear the notebooks
    python .githooks/clear_notebooks.py $notebooks
    # Re-add notebooks to staging area
    git add $notebooks
fi